### ISSUE TITLE
A contract class method specifying keyrest params can be satisfied by a method specifying an optional key arg with the same name

### ISSUE THREAD

**Issue by KevinBrowne** [Sage/sinject#36]
This contract states that `#foo` _must_ accept any number of keyword arguments:
```Ruby
class Contract
  def foo(bar, **kwargs); end
end
```

This class does not satisfy the contract because it does not accept any number of keyword arguments, it accepts precisely two:
```Ruby
class Concrete
  def foo(bar, kwargs: nil); end
end
```

However, the contract validation will accept the class:

On the other hand, it will _not_ accept this one because `kwargs` is `keyreq`:
```Ruby
class Concrete
  def foo(bar, kwargs:); end
end
```

Introduced by #35.

```Ruby
irb(main):001> container = Sinject::Container.new(false)
=> #<Sinject::Container:0x00007f060797e6b8 …>
irb(main):002* class Contract
irb(main):003*   def foo(bar, **kwargs); end
irb(main):004> end
=> :foo
irb(main):005* class Allowed
irb(main):006*   def foo(bar, kwargs: nil) = nil
irb(main):007> end
=> :foo
irb(main):008* class NotAllowed
irb(main):009*   def foo(bar, kwargs:) = nil
irb(main):010> end
=> :foo
irb(main):011> container.register(key: :allowed, class: Allowed, contract: Contract)
=> true
irb(main):012> container.register(key: :not_allowed, class: NotAllowed, contract: Contract)
/workspace/src/sinject/lib/sinject/container.rb:129:in `block in validate_contract': The method signature of method: 'foo' does not match the contract parameters: 'kwargs' (Sinject::DependencyContractInvalidParametersException)
```

**Comment by KevinBrowne** [comment]
An example of how the class does not implement the contract:
```Ruby
require 'sinject'

class Contract
  def foo(bar, **rest) = nil
end

class ValidImpl
  def foo(bar, **rest)
    puts "bar is #{bar}"
    rest.each { |k, v| puts "#{k} is #{v}" }
  end
end

class InvalidImpl
  def foo(bar, rest: 'wut?')
    puts "bar is #{bar} and rest is #{rest}"
  end
end

container = Sinject::Container.new(false)
container.register(key: :valid, class: ValidImpl, contract: Contract)
container.register(key: :invalid, class: InvalidImpl, contract: Contract)

container.get(:valid).foo('hello')
bar is hello

container.get(:valid).foo('hello', fee: 'fi', fo: 'fum')
bar is hello
fee is fi
fo is fum

container.get(:invalid).foo('hello')
bar is hello and rest is wut?

container.get(:invalid).foo('hello', fee: 'fi', fo: 'fum')
(irb):11:in `foo': unknown keywords: :fee, :fo (ArgumentError)
        from (irb):21:in `<main>'
        from <internal:kernel>:187:in `loop'
        from ./bin/console:14:in `<main>'
```
